### ISSUE TITLE
integration requirements not met by BSU submission

### ISSUE THREAD

**Issue by giodegas** [EMICVL/EMICVL_BSU#1]
3. The file is a Unity exported zip file.
4. There is no name of the package.
6. The folder structure is not compliant. Are missing _Sprites_ and _Sounds_ subfolders.
7. Extra content is not removed

**Comment by raminrahimzada** [comment]
Changed Package name as "EMICVL_BSU"
Added missing folders
Removed unused assets
Finally exported as UnityPackage file  "EMICVL_BSU_Releasev2.0"
You can find exported package  in description
