### ISSUE TITLE
release 2.0 integration requirements not met

### ISSUE THREAD

**Issue by giodegas** [EMICVL/EMICVL_BSU#2]
Providing the package as externally linked file to shared could storage, an MD5 code should be calculated, copied and pasted after the link to the file in the GitHub ReadMe. You can use [WinMD5](http://www.winmd5.com) to calculatet it , after exporting the Unity package.

6. Folder structures. Missing subfolders: Textures, Prefabs, AdditionalAsset X (with all additional assetes needed for the level, for example PyroParticle?) . Also the zip file still contains a lot of extra content not needed (Editor .., Library and so on..). 

9 Standard assets issue. Please read point 9 from [Intregration Requirements](http://github.com/EMICVL/ProjectDocumentation/blob/master/Integration_requirements.md)

13. A License file should be also present in the Unity package. Try using an empty C# script with licese text in a long comment delimited with /* */.

**Comment by giodegas** [comment]
for the license file, you can also do this: save it as a License.txt, then drag and drop inside the Assets/Scene folder in Unity

**Comment by raminrahimzada** [comment]
I have created "AdditionalAssets" folder containing my auxiliary assets such as <PyroParticle> etc. 
and  removed Editor  based scripts with folders 
Rechecked all solution and removed remaining unused assets
For License agreement i have License.txt in my "Assets\Scenes" folder 
Replaced my  custom FPS  controller  to standard FPS controller of Unity because - common project's FPS controller will be used instead of mine - no need to FPS confusing
And Finally I have updated github readme.md file and replaced new version (v3.0)  of level package file also added its MD5 hash after it 
I hope all requirements  will met now by version 3.0

**Comment by giodegas** [comment]
We are almost there. But still there are assets inside not necessary like the grayed Library folder with some asset from Facebook, as you can see in the picture, and the ThirdPersonCharacter contains an avatar, and it is not clear how is used in the project. If the avatar is needed, then make two separate packages, one without the entire Standard Assets folder and one containing these assets just limited to the avatar, as exlained in point 9: "IN CASE IF LEVEL PROJECT AUTHORS USE THE STANDARD AVATAR FROM THE STANDARD UNITY ASSET, THEY SHOULD PROVIDE FOR ASSEMBLING TWO VERSIONS OF PROJECT LEVEL: ONE WITH AN AVATAR AND THE OTHER ONE WITHOUT AN AVATAR. ALL CONTENT OF THE STANDARD UNITY ASSET SHOULD BE REMOVED FROM THE VERSION “WITHOUT AN AVATAR”. STANDARD ASSET IS ALREADY PRESENT IN THE CORE OF JOINT PROJECT"

<img width="412" alt="schermata 2017-11-08 alle 07 12 48" src="https://user-images.githubusercontent.com/6838625/32534239-fa36edca-c454-11e7-9a0e-2a39e0dd43f2.png">

The version without Standard Assets should be exported with selections as in the following picture:
<img width="428" alt="schermata 2017-11-08 alle 07 21 01" src="https://user-images.githubusercontent.com/6838625/32534399-b37104e2-c455-11e7-9c8d-2a4b4fd67428.png">

The hidden Library folder should not be in any package.
So you should produce to separated package files:

1. EMICVL_BSU_Release_vX          ( _without Standard Assets folder_ )

2. EMICVL_BSU_Release_SA_vX   ( _with the Standard Assets folder only those assets really nedded for the scene/level to work_ )

**Comment by raminrahimzada** [comment]
Finally I have  updated v3.1 containing two unity package files :
One of them contains Standard Assets and the other not
Removed all assets shown as unchecked in above pictures
 
MD5 sum  of each of file provided in readme file of project

**Comment by giodegas** [comment]
requirements appear to be met by release 3.1 MD5

**Comment by giodegas** [comment]
There are errors importing as reported from ONU.

**Comment by giodegas** [comment]
<img width="950" alt="schermata 2017-11-09 alle 20 16 29" src="https://user-images.githubusercontent.com/6838625/32624913-040f97ac-c58b-11e7-90ec-abbc9931ad1f.png">

Error: _Mesh doesn't have albedo UVs. Please create them in your modelling package._

**Comment by giodegas** [comment]
![errors_1](https://user-images.githubusercontent.com/6838625/32624986-47283bde-c58b-11e7-9184-7d514a07447a.jpg)
![error_2](https://user-images.githubusercontent.com/6838625/32624994-4c79b36a-c58b-11e7-8685-738ff75b6d16.jpg)

**Comment by raminrahimzada** [comment]
I rebuilt my models UV cache with my modelling software and re-imported  them 
also moved newly used assets to Additional Assets folder
For testing purpose i have imported both packages separately  in an empty unity project and  got success
So you can find new version (v3.2) with SA edition having their md5 sums in projects readme

**Comment by giodegas** [comment]
_Additional Assets_ folder is too complex, it should not have multiple inner levels. Only including very NECESSARY assets that canno be put into the requested folder structure as required , like espressed in pont 6:

6. Content of the level project should have the following structure (folders) to be used in the project:

    * Animation (level animation files)
    * Textures (level texture files)
    * Materials (level material files)
    * Models (models used on the level)
    * Prefabs (prefabs used on the level)
    * Scenes (the game levels including a license text file)
    * Sounds (sound files used on the level)
    * Scripts (scripts used on the level)
    * Sprites (sprites used on the level)
    * Additional assets (as a separate folder including all assets necessary to the scenario to work)

Still a lot of not necessary extra content is still present in the _Additional Assets_ folder.

**Comment by raminrahimzada** [comment]
Simplified Additional Assets and other folders so there is no sub-folder in each primary folder also  no unused assets
So Current Version is  4.0 You can find in projects readme

**Comment by giodegas** [comment]
Beta 4.0 appears to met the integration requirements.

**Comment by giodegas** [comment]
During integration import  there are still conflicts with Standard Assets from Unity

**Comment by raminrahimzada** [comment]
Can I have screenshots ( or error logs will be better if possible ) attached  ?

**Comment by giodegas** [comment]
Is it possible to have submitted a new version?

**Comment by raminrahimzada** [comment]
Of course,
Renamed full solution assets (except SA files) as  BSU_* and re-exported as v4.0.3 (with/without SA) is now available on project page

**Comment by giodegas** [comment]
the scene and folder structure appears ok, but I could not find a License.txt file.

**Comment by giodegas** [comment]
after import I mean, it ok in the GitHub repo, but it should also copied inside the _Scene_ folder with including a link to the repo
